management:
  server:
    port: 8089
  endpoint:
    metircs:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info

client:
  checkTimeout: 50000
  urls:
    - "http://localhost:8085/actuator/health"
    #- "http://localhost:8088/api/v1/authors"

